### ISSUE TITLE
关于代码用到的数据集

### ISSUE THREAD

**Issue by szz34** [tsinghua-fib-lab/City-Camera-Trajectory-Data#1]
您好，关于该代码要用到的数据集：“The .csv files as the proposed dataset. Please download from our Figshare repository.”

我没有找到相关的下载地址...请问哪里可以下载到这些数据文件？

另外请问“City-scale Vehicle Trajectory Data From Traffic Camera Videos.”这篇paper哪里可以看到...

感谢您指点迷津！

**Comment by YuFudan** [comment]
您好，这篇文章正在投稿中，包括paper和figshare的repo都还没有公开的链接，仅供审稿人在投稿系统中查看。之后有动态会随时更新~

**Comment by YuFudan** [comment]
您好，文章已被在线发表，文章和数据集的链接已更新在README中了~
